config/routes.rb
Rails.application.routes.draw do
  devise_for :psychologists
  root to: 'home#index'

  resources :participants, only: %i[show new create], shallow: true do
    resources :participant_instruments, only: %i[create] do
      get 'validation', to: 'participants#validation'
      post 'validate_participant', to: 'participants#validate_participant'
      get 'questionnaire', to: 'instruments#load_questionnaire'
      post 'submit', to: 'answers#create'
      get 'results', to: 'results#show'
    end
  end

  get 'instrument_completion', to: 'instruments#completion'
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :psychologist

  has_many :participant_instruments, dependent: :destroy
  has_many :instruments, through: :participant_instruments

  before_validation :sanitize_cpf

  validate :validate_cpf

  validates :name, :cpf, :email, :date_of_birth, presence: true
  validates :cpf, :email, uniqueness: true
  validates :email, format: URI::MailTo::EMAIL_REGEXP

  def valid_data?(data)
    symbolized_data = data.to_h.symbolize_keys

    same_name?(symbolized_data[:name]) &&
      same_cpf?(symbolized_data[:cpf]) &&
      same_email?(symbolized_data[:email]) &&
      same_date_of_birth?(symbolized_data[:date_of_birth])
  end

  private

  def sanitize_cpf
    cpf.gsub!(/[^\d]/, '')
  end

  def validate_cpf
    errors.add(:cpf, I18n.t(:invalid_cpf)) unless cpf.blank? || CPF.valid?(cpf)
  end

  def same_name?(name_to_compare)
    name.downcase == name_to_compare.downcase
  end

  def same_cpf?(cpf_to_compare)
    cpf.gsub(/[^\d]/, '') == cpf_to_compare.gsub(/[^\d]/, '')
  end

  def same_email?(email_to_compare)
    email.downcase == email_to_compare.downcase
  end

  def same_date_of_birth?(date_of_birth_to_compare)
    date_of_birth.to_date == date_of_birth_to_compare.to_date
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :authorize, only: %i[show]

  skip_before_action :authenticate_psychologist!, only: %i[validation validate_participant]

  def show
    @options_for_new_instruments = Instrument.all
  end

  def new
    @participant = Participant.new
  end

  def create
    @participant = current_psychologist.participants.build(participant_params)

    return redirect_to @participant, notice: t('.success') if @participant.save

    flash[:alert] = "#{t('.failure')} #{@participant.errors.full_messages.to_sentence}"
    render :new, status: :unprocessable_entity
  end

  def validation
    @participant = Participant.new
  end

  def validate_participant
    @participant = ParticipantInstrument.find(params[:participant_instrument_id]).participant

    if @participant.valid_data?(participant_params)
      store_validation
      return redirect_to participant_instrument_questionnaire_path(params[:participant_instrument_id])
    end

    flash.now[:alert] = t('.incorrect_data')
    render :validation, status: :unauthorized
  end

  private

  def authorize
    @participant = Participant.find(params[:id])
    redirect_to root_path unless @participant.psychologist == current_psychologist
  end

  def participant_params
    params.require(:participant).permit(:name, :cpf, :email, :date_of_birth)
  end

  def store_validation
    session[:participant_validated] = true
  end
end

app/views/participants/_form.html.erb
<%= form_with(model: participant, url:, class: 'w-25') do |f| %>
  <div class="d-flex flex-column mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name,
      required: true,
      placeholder: 'ex.: José Maria dos Santos',
      class: 'form-control' %>
  </div>

  <div class="d-flex flex-column mb-3">
    <%= f.label :cpf, class: 'form-label' %>
    <%= f.text_field :cpf,
      required: true,
      placeholder: 'ex.: 01234567890',
      class: 'form-control' %>
  </div>

  <div class="d-flex flex-column mb-3">
    <%= f.label :email, class: 'form-label' %>
    <%= f.email_field :email,
      required: true,
      placeholder: 'ex.: exemplo@email.com',
      class: 'form-control' %>
  </div>

  <div class="d-flex flex-column mb-3">
    <%= f.label :date_of_birth, class: 'form-label' %>
    <%= f.date_field :date_of_birth,
      required: true,
      class: 'form-control' %>
  </div>

  <div class="text-center">
    <%= f.submit btn_text, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/participants/_participant.html.erb
<section class="container w-50 card p-3 mb-5" id="participant_info">
  <div class="row mb-3 justify-content-around">
    <div class="col">
      <div class="text-muted"><%= Participant.model_name.human %></div>
      <div class="fs-5"><%= participant.name %></div>
    </div>
    <div class="col text-end">
      <div class="text-muted"><%= Participant.human_attribute_name(:cpf) %></div>
      <div class="fs-5"><%= participant.cpf %></div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="text-muted"><%= Participant.human_attribute_name(:email) %></div>
      <div class="fs-5"><%= participant.email %></div>
    </div>
    <div class="col text-end">
      <div class="text-muted"><%= Participant.human_attribute_name(:date_of_birth) %></div>
      <div class="fs-5"><%= l(participant.date_of_birth) %></div>
    </div>
  </div>
</section>

app/views/participants/_participant_instruments_table.html.erb
<h1 class="fs-3 mb-3"><%= t(:assigned_instruments) %></h1>
<table class="table table-striped">
  <tr>
    <th><%= Instrument.human_attribute_name(:name) %></th>
    <th class="text-end">
      <%= ParticipantInstrument.human_attribute_name(:status) %>
    </th>
    <th class="text-end">
      <%= ParticipantInstrument.human_attribute_name(:created_at) %>
    </th>
    <th class="text-end">
      <%= ParticipantInstrument.human_attribute_name(:finished_at) %>
    </th>
    <th class="text-end">
      <%= ParticipantInstrument.human_attribute_name(:score) %>
    </th>
    <th></th>
  </tr>

  <% participant_instruments.each do |part_inst| %>
    <tr>
      <td><%= part_inst.instrument.name %></td>
      <td class="text-end"><%= ParticipantInstrument.human_attribute_name("status.#{part_inst.status}") %></td>
      <td class="text-end"><%= l(part_inst.created_at.to_date) %></td>
      <td class="text-end"><%= l(part_inst.finished_at.to_date) if part_inst.finished? && part_inst.finished_at %></td>
      <td class="text-end"><%= part_inst.score %></td>
      <td class="text-end"><%= link_to t(:details), participant_instrument_results_path(part_inst) %></td>
    </tr>
  <% end %>
</table>

app/views/participants/new.html.erb
<h1 class="mb-4">Novo <%= Participant.model_name.human %></h1>

<%= render partial: 'form', locals: { participant: @participant,
                                      url: participants_path,
                                      btn_text: t(:save) } %>

app/views/participants/show.html.erb
<%= render @participant %>

<% if @options_for_new_instruments.any? %>
  <%= form_with(model: [@participant, ParticipantInstrument.new],
                class: 'd-flex justify-content-between mb-5') do |f| %>
    <div class="d-flex justify-content-between gap-5 w-100">
      <%= f.label :instrument_id, class: 'd-none' %>
      <%= collection_select :participant_instrument, :instrument_id,
        @options_for_new_instruments, :id, :name,
        prompt: t(:select_prompt), required: true, class: 'me-3' %>
      <%= f.submit t(:assign_new), class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

<% if @participant.participant_instruments.any? %>
  <%= render partial: 'participant_instruments_table',
    locals: { participant_instruments: @participant.participant_instruments } %>
<% else %>
  <p><%= t(:no_instruments_assigned) %></p>
<% end %>

app/views/participants/validation.html.erb
<div class="alert alert-warning">Valide os dados antes de prosseguir para o questionário</div>

<%= render partial: 'form', locals: { participant: @participant,
                                      url: participant_instrument_validate_participant_path,
                                      btn_text: t(:next) } %>