config/routes.rb
Rails.application.routes.draw do
  devise_for :psychologists
  root to: 'home#index'

  resources :participants, only: %i[show new create], shallow: true do
    resources :participant_instruments, only: %i[create] do
      get 'validation', to: 'participants#validation'
      post 'validate_participant', to: 'participants#validate_participant'
      get 'questionnaire', to: 'instruments#load_questionnaire'
      post 'submit', to: 'answers#create'
      get 'results', to: 'results#show'
    end
  end

  get 'instrument_completion', to: 'instruments#completion'
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :authorize, only: %i[show]

  def show; end

  private

  def authorize
    @participant_instrument = ParticipantInstrument.find(params[:participant_instrument_id])
    redirect_to root_path unless @participant_instrument.psychologist == current_psychologist
  end
end

app/views/results/show.html.erb
<%= render partial: 'participants/participant',
           locals: { participant: @participant_instrument.participant} %>

<section class="w-50">
  <div>
    <h1 class="fs-3"><%= @participant_instrument.instrument.name %></h1>
    <p><%= @participant_instrument.instrument.description %></p>
  </div>

  <div class="d-flex justify-content-between mb-3">
    <div class="d-flex flex-column">
      <span class="text-muted fw-light">
        <%= ParticipantInstrument.human_attribute_name(:status) %>
      </span>
      <span>
        <%= ParticipantInstrument.human_attribute_name("status.#{@participant_instrument.status}") %>
      </span>
    </div>

    <div class="d-flex flex-column">
      <span class="text-muted fw-light">
        <%= t(:assignment_date_label) %>
      </span>
      <span><%= l(@participant_instrument.created_at.to_date) %></span>
    </div>
    
    <% if @participant_instrument.finished? %>
      <div class="d-flex flex-column">
        <span class="text-muted fw-light">
          <%= t(:finish_date_label) %>
        </span>
        <span><%= l(@participant_instrument.finished_at.to_date) %></span>
      </div>
    <% end %>
  </div>
  
  <% if @participant_instrument.finished? %>
    <div class="d-flex flex-column">
      <span class="text-muted fw-light">
        <%= t(:total_score) %>
      </span>
      <span class="fs-3"><%= @participant_instrument.score %></span>
    </div>

    <hr class="border border-2 opacity-75 w-100">
  <% end %>

  <% if @participant_instrument.finished? %>
    <div id="participant_answers">
      <% @participant_instrument.answers.each_with_index do |answer, index| %>
        <div id="question<%= index + 1%>" class="mb-3">
          <div class="mb-1">
            <span class="text-muted fw-light"><%= index + 1 %>.</span>
            <span><%= answer.question.description %></span>
          </div>
          <div>
            <span class="text-muted fw-light"><%= t(:selected_option) %>:</span>
            <%= answer.option.description %>
          </div>
          <div>
            <span class="text-muted fw-light"><%= t(:option_weight) %>:</span>
            <%= answer.weight %>
          </div>
        </div>
      <% end %>

      <hr class="border border-2 opacity-75 w-100 mt-3">
    </div>
  <% end %>
</section>

<%= link_to t(:back), participant_path(@participant_instrument.participant), class: 'mb-5' %>