config/routes.rb
Rails.application.routes.draw do
  devise_for :psychologists
  root to: 'home#index'

  resources :participants, only: %i[show new create], shallow: true do
    resources :participant_instruments, only: %i[create] do
      get 'validation', to: 'participants#validation'
      post 'validate_participant', to: 'participants#validate_participant'
      get 'questionnaire', to: 'instruments#load_questionnaire'
      post 'submit', to: 'answers#create'
      get 'results', to: 'results#show'
    end
  end

  get 'instrument_completion', to: 'instruments#completion'
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  class QuestionsLimitExceeded < ActiveRecord::ActiveRecordError; end

  MAX_QUESTIONS = 5

  has_many :participant_instruments, dependent: :destroy
  has_many :questions, dependent: :destroy, before_add: :check_questions_limit

  validates :name, :description, presence: true

  private

  def check_questions_limit(_question)
    raise QuestionsLimitExceeded if questions.count >= MAX_QUESTIONS
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  skip_before_action :authenticate_psychologist!, only: %i[load_questionnaire completion]

  def load_questionnaire
    unless participant_validated?
      return redirect_to participant_instrument_validation_path(params[:participant_instrument_id])
    end

    @participant_instrument = ParticipantInstrument.find(params[:participant_instrument_id])
    redirect_finished_instrument
  end

  def completion; end

  private

  def redirect_finished_instrument
    return if @participant_instrument.pending?

    redirect_to instrument_completion_path, notice: t('.already_submitted')
  end

  def participant_validated?
    session[:participant_validated]
  end
end

app/views/instruments/completion.html.erb
<p>Respostas salvas com sucesso!
Obrigado por responder ao questionário.</p>

app/views/instruments/load_questionnaire.html.erb
<%= render partial: 'participants/participant',
           locals: { participant: @participant_instrument.participant } %>

<%= form_with(url: participant_instrument_submit_path(@participant_instrument),
              method: :post, class: 'w-50') do |f| %>
  <% @participant_instrument.questions.each_with_index do |q, i| %>
    <div id="question<%= i + 1 %>" class="card p-3 m-auto mb-3">
      <p class="fw-semibold"><%= q.description %></p>
      <% q.options.each do |o| %>
        <div class="d-flex gap-3">
          <%= f.radio_button "answers[#{i}][option_id]", o.id %>
          <%= f.label "answers[#{i}][option_id]_#{o.id}", o.description %>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= f.submit t(:save), class: 'btn btn-primary d-block m-auto my-4' %>
<% end %>