config/routes.rb
Rails.application.routes.draw do
  devise_for :psychologists
  root to: 'home#index'

  resources :participants, only: %i[show new create], shallow: true do
    resources :participant_instruments, only: %i[create] do
      get 'validation', to: 'participants#validation'
      post 'validate_participant', to: 'participants#validate_participant'
      get 'questionnaire', to: 'instruments#load_questionnaire'
      post 'submit', to: 'answers#create'
      get 'results', to: 'results#show'
    end
  end

  get 'instrument_completion', to: 'instruments#completion'
end

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar bg-body-secondary mb-5">
  <div class="container-fluid px-5">
    <span class="navbar-text fw-bold fs-2">
      <%= link_to 'Vetor', root_path, class: 'text-decoration-none text-muted' %>
    </span>
    <% if psychologist_signed_in? %>
      <div class="d-flex gap-5 align-items-center">
        <%= link_to t(:my_participants), root_path, class: 'text-decoration-none text-muted fw-semibold' %>
        <%= link_to t(:register_participant), new_participant_path, class: 'text-decoration-none text-muted fw-semibold' %>
        <%= button_to t(:log_out), destroy_psychologist_session_path, method: :delete, class: 'btn btn-danger' %>
      </div>
    <% else %>
      <%= link_to t(:log_in), new_psychologist_session_path %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vetor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <main class="container d-flex flex-column align-items-center">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>